#!/usr/bin/env python3
"""The Source — generate and validate docs/SYSTEM_TRUTH.md from the brain.

The single source of truth is *generated* from the live brain (agents,
hooks), never hand-maintained, so it cannot drift. Run without args
to regenerate; pass {"check": true} (or --check) to validate sync and fail
(exit 1) if the file is stale.

Usage:
  bin/matrix hooks the_source            # regenerate docs/SYSTEM_TRUTH.md
  bin/matrix hooks the_source '{"check":true}'   # validate it is in sync
"""

import os
import sys

from _common import emit, load_yaml_strict, parse_frontmatter as _parse_frontmatter, read_input, resolve_root


def parse_frontmatter(path):
    return (data := _parse_frontmatter(path)).get("name", os.path.splitext(os.path.basename(path))[0]), data.get("description", "")


def list_md(dirpath):
    if not os.path.isdir(dirpath):
        return []
    return sorted(f for f in os.listdir(dirpath) if f.endswith(".md"))


def live_hooks(root):
    hooks_dir = os.path.join(root, "hooks")
    return sorted(
        f[:-3] for f in os.listdir(hooks_dir)
        if f.endswith(".py") and f != "_common.py"
    ) if os.path.isdir(hooks_dir) else []


def parse_ship_manifest(path):
    """Return ship manifest frontmatter as a dict."""
    return _parse_frontmatter(path)


def live_ships(root):
    """Return list of ship manifests from brain/subsystems/*/AGENTS.md."""
    ships_dir = os.path.join(root, "brain", "subsystems")
    if not os.path.isdir(ships_dir):
        return []
    out = []
    for name in sorted(os.listdir(ships_dir)):
        agents_md = os.path.join(ships_dir, name, "AGENTS.md")
        if not os.path.isfile(agents_md):
            continue
        m = parse_ship_manifest(agents_md)
        if m.get("ship"):
            out.append(m)
    return out


def config_flags_missing(root):
    """Return (missing_flags, load_error) for adapters/devin/config.yaml (depth <= 2).

    An unreadable config is a real error, never a silent [] (lesson 71) — it
    propagates as load_error so check() fails ok=False instead of passing.
    """
    config_path = os.path.join(root, "adapters", "devin", "config.yaml")
    devin_md_path = os.path.join(root, "DEVIN.md")
    cfg, load_error = load_yaml_strict(config_path)
    if load_error is not None:
        return [], load_error
    if not isinstance(cfg, dict):
        return [], None
    keys = set()
    for top_key, top_val in cfg.items():
        keys.add(top_key)
        if isinstance(top_val, dict):
            for child_key in top_val:
                keys.add(child_key)
    devin_text = ""
    try:
        if os.path.isfile(devin_md_path):
            with open(devin_md_path, encoding="utf-8") as fh:
                devin_text = fh.read()
    except Exception:
        pass
    return sorted(k for k in keys if k not in devin_text), None


def generate(root):
    agents_dir = os.path.join(root, "brain", "agents")

    agents = []
    for f in list_md(agents_dir):
        agents.append(parse_frontmatter(os.path.join(agents_dir, f)))

    hooks = live_hooks(root)

    out = []
    out.append("# SYSTEM_TRUTH — The Source")
    out.append("")
    out.append("> Generated by `hooks/the_source.py` from the live brain. **Do not edit by hand** — run `bin/matrix hooks the_source` to regenerate. Validated for drift via `{\"check\": true}`.")
    out.append("")
    out.append("## Roster (live)")
    out.append("")
    out.append("| Agent | Description |")
    out.append("|---|---|")
    for name, desc in agents:
        out.append(f"| **{name}** | {desc} |")
    out.append("")
    out.append("## Fleet (live)")
    out.append("")
    ships = live_ships(root)
    if ships:
        out.append("| Ship | Captain | Crew |")
        out.append("|---|---|---|")
        for m in ships:
            crew = m.get("crew", [])
            if isinstance(crew, list):
                crew_str = ", ".join(crew)
            else:
                crew_str = str(crew)
            out.append(f"| **{m.get('ship', '')}** | {m.get('captain', '')} | {crew_str} |")
    else:
        out.append("- (none registered)")
    out.append("")
    out.append("## Enforcement hooks (Seraph, live)")
    out.append("")
    for h in hooks:
        out.append(f"- `{h}`")
    out.append("")
    out.append("## Layers")
    out.append("")
    out.append("- **Layer 1** — `bin/matrix` + `hooks/` + `brain/state/` (orchestration, enforcement, state)")
    out.append("- **Layer 2** — `brain/agents/` + `AGENTS.md` (agnostic intelligence core)")
    out.append("- **Layer 3** — `adapters/` (the Trainman; per-CLI bindings)")
    out.append("")
    return "\n".join(out) + "\n"


def check(root, check=True):
    """Validate (or regenerate) docs/SYSTEM_TRUTH.md and return a result dict.

    This entry point is safe to call from boot_warn because it never calls
    sys.exit. The surrounding caller is responsible for catching exceptions.
    """
    target = os.path.join(root, "docs", "SYSTEM_TRUTH.md")
    content = generate(root)

    if check:
        existing = ""
        if os.path.isfile(target):
            with open(target, encoding="utf-8") as fh:
                existing = fh.read()
        in_sync = existing.strip() == content.strip()
        missing_flags, config_load_error = config_flags_missing(root)
        ok = in_sync and not missing_flags and config_load_error is None
        if config_load_error is not None:
            note = f"adapters/devin/config.yaml is unreadable: {config_load_error}"
        elif not in_sync:
            note = "SYSTEM_TRUTH.md is stale"
        elif missing_flags:
            note = "DEVIN.md omits a config flag"
        else:
            note = "in sync"
        return {
            "hook": "the_source",
            "ok": ok,
            "mode": "check",
            "in_sync": in_sync,
            "config_flags_missing": missing_flags,
            "config_load_error": str(config_load_error) if config_load_error else None,
            "target": target,
            "note": note,
        }

    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(content)
    return {
        "hook": "the_source",
        "ok": True,
        "mode": "generate",
        "target": target,
        "agents": len(content.split("**")) // 2,
    }


def main():
    data = read_input()
    check_mode = bool(data.get("check")) or "--check" in sys.argv
    root = resolve_root()
    try:
        result = check(root, check=check_mode)
    except Exception as exc:
        result = {
            "hook": "the_source",
            "ok": False,
            "mode": "check" if check_mode else "generate",
            "target": os.path.join(root, "docs", "SYSTEM_TRUTH.md"),
            "note": f"the_source check failed: {exc}",
        }
    emit(result)


if __name__ == "__main__":
    main()
