#!/usr/bin/env python3
"""The Source — generate and validate docs/SYSTEM_TRUTH.md from the brain.

The single source of truth is *generated* from the live brain (agents,
workflows, hooks), never hand-maintained, so it cannot drift. Run without args
to regenerate; pass {"check": true} (or --check) to validate sync and fail
(exit 1) if the file is stale.

Usage:
  bin/matrix hooks the_source            # regenerate docs/SYSTEM_TRUTH.md
  bin/matrix hooks the_source '{"check":true}'   # validate it is in sync
"""

import os
import re
import subprocess
import sys

from _common import emit, read_input, resolve_root


def parse_frontmatter(path):
    """Return (name, description) from a markdown agent's YAML frontmatter."""
    name = os.path.splitext(os.path.basename(path))[0]
    desc = ""
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    if lines and lines[0].strip() == "---":
        for ln in lines[1:]:
            if ln.strip() == "---":
                break
            if ln.startswith("name:"):
                name = ln.split(":", 1)[1].strip()
            elif ln.startswith("description:"):
                desc = ln.split(":", 1)[1].strip()
    return name, desc


def list_md(dirpath):
    if not os.path.isdir(dirpath):
        return []
    return sorted(f for f in os.listdir(dirpath) if f.endswith(".md"))


def live_hooks(root):
    hooks_dir = os.path.join(root, "hooks")
    return sorted(
        f[:-3] for f in os.listdir(hooks_dir)
        if f.endswith(".py") and not f.startswith("_")
    ) if os.path.isdir(hooks_dir) else []


def onboarding_coverage(root):
    """Return whether onboarding.html covers the current live surface."""
    onboarding_path = os.path.join(root, "onboarding.html")
    with open(onboarding_path, encoding="utf-8") as fh:
        onboarding = fh.read()

    agents_dir = os.path.join(root, "brain", "agents")
    agents = [
        parse_frontmatter(os.path.join(agents_dir, filename))[0]
        for filename in list_md(agents_dir)
    ]
    hooks = live_hooks(root)

    proc = subprocess.run(
        [os.path.join(root, "bin", "matrix"), "help"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    # Help commands begin with two spaces and a lowercase hyphenated token.
    commands = re.findall(r"(?m)^  ([a-z]+(?:-[a-z]+)*)\s+", proc.stdout)

    missing = {
        "agents": [name for name in agents if name not in onboarding],
        "hooks": [name for name in hooks if name not in onboarding],
        "commands": [name for name in commands if name not in onboarding],
    }
    return {"ok": not any(missing.values()), "missing": missing}


def generate(root):
    agents_dir = os.path.join(root, "brain", "agents")
    wf_dir = os.path.join(root, "brain", "workflows")

    agents = []
    for f in list_md(agents_dir):
        agents.append(parse_frontmatter(os.path.join(agents_dir, f)))

    workflows = [f[:-3] for f in list_md(wf_dir) if f.lower() != "readme.md"]
    hooks = live_hooks(root)

    out = []
    out.append("# SYSTEM_TRUTH — The Source")
    out.append("")
    out.append("> Generated by `hooks/the_source.py` from the live brain. **Do not edit by hand** — run `bin/matrix hooks the_source` to regenerate. Validated for drift via `{\"check\": true}`.")
    out.append("")
    out.append("## Roster (live)")
    out.append("")
    out.append("| Agent | Description |")
    out.append("|---|---|")
    for name, desc in agents:
        out.append(f"| **{name}** | {desc} |")
    out.append("")
    out.append("## Workflows (live)")
    out.append("")
    if workflows:
        for w in workflows:
            out.append(f"- `{w}`")
    else:
        out.append("- (none yet)")
    out.append("")
    out.append("## Enforcement hooks (Seraph, live)")
    out.append("")
    for h in hooks:
        out.append(f"- `{h}`")
    out.append("")
    out.append("## Layers")
    out.append("")
    out.append("- **Layer 1** — `bin/matrix` + `hooks/` + `brain/state/` (orchestration, enforcement, state)")
    out.append("- **Layer 2** — `brain/agents/` + `brain/workflows/` + `AGENTS.md` (agnostic intelligence core)")
    out.append("- **Layer 3** — `adapters/` (the Trainman; per-CLI bindings)")
    out.append("")
    return "\n".join(out) + "\n"


def main():
    data = read_input()
    check = bool(data.get("check")) or "--check" in sys.argv
    root = resolve_root()
    target = os.path.join(root, "docs", "SYSTEM_TRUTH.md")
    content = generate(root)

    if check:
        existing = ""
        if os.path.isfile(target):
            with open(target, encoding="utf-8") as fh:
                existing = fh.read()
        in_sync = existing.strip() == content.strip()
        coverage = onboarding_coverage(root)
        ok = in_sync and coverage["ok"]
        emit({
            "hook": "the_source",
            "ok": ok,
            "mode": "check",
            "in_sync": in_sync,
            "onboarding_coverage": coverage,
            "target": target,
            "note": "in sync" if ok else "SYSTEM_TRUTH.md is stale or onboarding.html is missing live coverage",
        })
        return

    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as fh:
        fh.write(content)
    emit({
        "hook": "the_source",
        "ok": True,
        "mode": "generate",
        "target": target,
        "agents": len(content.split("**")) // 2,
    })


if __name__ == "__main__":
    main()
